export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR';
export const SET_LOGIN_SUCCESS = 'SET_LOGIN_SUCCESS';
export const SET_REGISTRATION_ERROR = 'SET_REGISTRATION_ERROR';
export const SET_REGISTRATION_SUCCESS = 'SET_REGISTRATION_SUCCESS';
