export const SET_SIGN_IN_ERROR = 'SET_SIGN_IN_ERROR';
export const SET_SIGN_UP_ERROR = 'SET_SIGN_UP_ERROR';
export const SET_SIGN_IN_SUCCESS = 'SET_SIGN_IN_SUCCESS';
export const SET_SIGN_UP_SUCCESS = 'SET_SIGN_UP_SUCCESS';
