export const SET_CAR_LIST = 'SET_CAR_LIST';
export const SET_BROCHURES = 'SET_BROCHURES';
export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_USER_EMAIL = 'SET_USER_EMAIL';
export const SET_USER_AGREE = 'SET_USER_AGREE';
export const SET_SUBMIT_STATUS = 'SET_SUBMIT_STATUS';
